# Generated by Django 3.1.4 on 2021-01-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210116_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(db_index=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
